// react-append-nodes/src/App.js
import React from 'react';

class App extends React.Component {
  constructor(props) {
    super(props)
    this.state = { nodes: [], time: 0 }
    this.total = 0
    this.n = 1000
    this.t1 = 0
    this.t2 = 0
  }
  componentWillUpdate() {
    this.t1 = performance.now()
  }
  componentDidUpdate() {
    this.t2 = performance.now()
    document.querySelector('#output').textContent = (this.t2 - this.t1) + 'ms'
  }
  run = () => {
    const newNodes = []
    for (let i = 0; i < this.n; i++) {
      newNodes.push(this.total + i)
    }
    this.total += this.n
    this.setState({
      nodes: [...this.state.nodes, ...newNodes]
    })
  }
  render() {
    return (
      <div className="App">
        <button onClick={this.run}>运行</button>
        <div id="output"></div>
        <div>{this.state.nodes.map(n => <div key={n}>{n}</div>)}</div>
      </div>
    );
  }
}


export default App;

// vue-append-notes/src/App.vue
<template>
<div id="app">
  <button @click="run">运行</button>
  <div ref="output"></div>
  <div>
    <div v-for="n in nodes" :key="n">{{n}}</div>
  </div>
</div>
</template>

<script>
export default {
  name: 'App',
  data() {
    return {
      n: 1000,
      nodes: []
    }
  },
  created() {
    this.t1 = 0
    this.t2 = 0
    this.total = 0
  },
  updated() {
    this.t2 = performance.now()
    this.$refs.output.textContent = this.t2 - this.t1 + 'ms'
  },
  methods: {
    run() {
      this.t1 = performance.now()
      for (let i = 0; i < this.n; i++) {
        this.nodes.push(this.total + i)
      }
      this.total += this.n
    }
  }
}
</script>

<style>

</style>
